---
# PLAY
# This playbook deploys all OpenShift objects to all namespaces
- name: Deploy application to cluster
  hosts: seed-hosts
  roles:
  - role: roles/openshift-applier/roles/openshift-applier
  